name = "Beta Create Magic"
author = "W0lverine_14"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e62a1bfc0fe9b95d572cc18a9c85dd1bfd8ac23852527f2f2b7606b21fbee0a"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
