name = "Beta Create Magic"
author = "W0lverine_14"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7b142b0b5a95c4d9997256a370644bc3be4010bfba7133d22cf17f5111adff5"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
