name = "Beta Create Magic"
author = "W0lverine_14"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03154ab3e9333fdafac4b62d71f5d9f19f5fd245eafbfbdf491595c2fb18cf16"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
