name = "Beta Create Magic"
author = "W0lverine_14"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3be8832051114611dd06c9dc6fe53fa47e5c9c5f069e4b71132229a9fd9f7530"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
