name = "Beta Create Magic"
author = "W0lverine_14"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "052f4c48967453597f55c3064b7fdc81272cb5bfb4dbe823c01dab73b706b503"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
